version: '3.7'

services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
            MONGO_INITDB_DATABASE: pipelineprod
        ports:
            - 27017:27017
        volumes:
            - ./mongo-init.js:/mongo_docker-entrypoint-initdb.d/mongo-init.js
            - /{SET_YOUR_DIRS}/PRE_data_pipeline/PRE_localdevharness/services/win/mongo:/data/db:rw
