Vagrant.configure("2") do |config|
  
  config.vm.define "master" do |master|
    master.vm.box = "hashicorp/bionic64"
    
    master.ssh.forward_agent = true

    master.vm.network "private_network", ip: "192.168.50.110",
      virtualbox__intnet: true
    master.vm.synced_folder ".", "/vagrant", type: "rsync"

    master.vm.network "forwarded_port", guest: 8080, host: 2280
    master.vm.network "forwarded_port", guest: 22, host: 2222
    master.vm.network "forwarded_port", guest: 7474, host: 7474
    master.vm.network "forwarded_port", guest: 7687, host: 7687

    master.vm.hostname = "ansiblemaster"
    master.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.cpus = 2
      vb.memory = "4096"
      vb.name = "ansiblemaster"
    end
    master.vm.provision "shell" do |shell|
      shell.path = "scripts/provision.sh"
    end
  end 
end

