Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"
  config.vm.provision "docker"
  config.vm.network "private_network", ip: "192.168.50.110",
    virtualbox__intnet: true
  config.vm.network :forwarded_port, guest: 80, host: 8000
  config.vm.network :forwarded_port, guest: 3306, host: 3306
  config.vm.provision :shell, path: "bootstrap.sh"
end
