Vagrant.configure("2") do |config|
   config.vm.box = "hashicorp/bionic64"
   config.vm.hostname = 'utility-server-1'
   config.vm.network 'public_network', bridge: 'Internet'
   config.vm.synced_folder ".", "/vagrant", disabled: true
   config.vm.provider "hyperv" do |vb|
      vb.memory = "4024"
      vb.cpus = 2	
      vb.vmname = 'utility-server-1'
      vb.mac = '00:35:10:00:00:05'
   end
end
